### PR TITLE
fix(solidity): parser update and keywords

### PR DESCRIPTION
**Pull request by sambacha**

### CODE REVIEW

**Comment by sambacha** [comment]
Error and From (also Global) are not per se keywords, so wondering more about this.

also heres reference https://github.com/ethereum/solidity/blob/5fe31737472cc593cc9957d24a964ebf5491cbeb/docs/units-and-global-variables.rst#reserved-keywords

**Comment by tintinweb** [comment]
hey @sambacha 🙌

thanks for the PR. I think we should revert the keywords to be as close as possible to https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SolidityParser.cpp#L509 just to make sure we do not diverge too much from the original compiler.

you might want to raise this question with ethereum/solidity. looks like some of your keywords should actually be in there 🤔 .

happy to merge, otherwise.

**Comment by tintinweb** [comment]
also looks like they removed parser support for `address.send{x eth}()`

testcase:  https://github.com/tintinweb/solidity-workspace/blob/master/examples/learnSolidity.sol#L61-L62
```solidity
msg.sender.send{1 ETH}(); //this is actually illegal
RandomContract(lol).doSomething{value: 1 ETH}();
```

now yields unhandled exception:

```
./js/solidity-workspace/node_modules/@solidity-parser/parser/dist/index.cjs.js:3252
    }, this) : t2.accept(this);
                  ^

TypeError: Cannot read properties of null (reading 'accept')
```

**Comment by tintinweb** [comment]
merging this, tracking the obscure error as https://github.com/tintinweb/solidity-workspace/issues/6 until upstream fix.

**Comment by sambacha** [comment]
> merging this, tracking the obscure error as https://github.com/tintinweb/solidity-workspace/issues/6 until upstream fix.

Thanks, did not see your earlier replies, my apologies!

**Pull request merged**
